name: Run Python Script

on:
  push:
    branches:
      - nandan7198-patch-1 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r Revolight/requirements.txt
      working-directory: ${{ github.workspace }}

    - name: Run Python script
      run: python Revolight/RevoLight.py  
      working-directory: ${{ github.workspace }}
